RDL/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('docs/', include('docs.urls')),
]

docs/urls.py
from django.urls import path
from . import views


app_name = 'docs'
urlpatterns = [
	# ** ex: /docs/
	path('', views.IndexView.as_view(), name='index'),

	# ** ex: /docs/1/
	path('<int:pk>/', views.ReporteView.as_view(), name='reporte'),

	# ** ex: /docs/1/pasos
	path('<int:id_reporte>/pasos/', views.pasos_reporte, name='pasos'),
]

AdminLTE3/models.py
from django.db import models

# Create your models here.

docs/models.py
from django.db import models
from django.conf import settings


class Servidor(models.Model):
	servidor = models.IntegerField(primary_key=True)
	ip = models.GenericIPAddressField(unique=True, verbose_name="ip del servidor")
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name_plural = "Servidores"
		ordering = ['servidor']

	def __str__(self):
		return '%s'% (self.servidor)


class Area(models.Model):
	nombre = models.CharField(max_length=50)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	
	class Meta:
		verbose_name_plural = "Areas"
		ordering = ['nombre']

	def __str__(self):
		return '%s'% (self.nombre)


class Dia(models.Model):
	id = models.SmallIntegerField(primary_key=True)
	dia = models.CharField(max_length=10)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name_plural = "Dias"
		ordering = ['id']

	def __str__(self):
		return '%s'% (self.dia)



class Solicitante(models.Model):
	nombre = models.CharField(max_length=30)
	apellido = models.CharField(max_length=30)
	area = models.ForeignKey(Area, on_delete=models.PROTECT)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name_plural = "Solicitantes"
		ordering = ['apellido']

	def __str__(self):
		return '%s %s'% (self.nombre, self.apellido)


class Reporte(models.Model):
	URGENTE = 0
	IMPORTANTE = 1
	MEDIA = 2
	BAJA = 3
	PRIORIDAD=(
		(URGENTE, 'Urgente'),
		(IMPORTANTE, 'Importante'),
		(MEDIA, 'Media'),
		(BAJA, 'Baja'),
	)

	nombre = models.CharField(max_length=50)
	prioridad = models.IntegerField(
		choices=PRIORIDAD,
		default=MEDIA
	)
	solicitante = models.ForeignKey(Solicitante, on_delete=models.PROTECT)
	responsable = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
	dias = models.ManyToManyField(
		Dia,
		verbose_name="dias de actualizacion"
	)
	hora_actualizacion = models.TimeField(verbose_name="hora de actualizacion")
	repeticion = models.SmallIntegerField(verbose_name="tiempo de repeticion (hrs)", null=True, blank=True)
	servidor = models.ForeignKey(Servidor, on_delete=models.PROTECT)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name_plural = "Reportes"
		ordering = ['nombre']

	def __str__(self):
		return '%s (%s)'% (self.nombre, self.solicitante)


class TipoPaso(models.Model):
	tipo = models.CharField(max_length = 50, verbose_name = "tipo de paso")

	def __str__(self):
		return '%s'% (self.tipo)


class Paso(models.Model):
	n_paso = models.SmallIntegerField()
	id_reporte = models.ForeignKey(Reporte, on_delete = models.CASCADE)
	nombre = models.CharField(max_length=40, verbose_name = "nombre del paso")
	tipo = models.ForeignKey(TipoPaso, on_delete = models.PROTECT, verbose_name = "tipo de paso")
	servidor = models.ForeignKey(Servidor, on_delete = models.PROTECT)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta():
		unique_together = ['n_paso', 'id_reporte']
		verbose_name_plural = "Pasos"
		ordering = ['id_reporte', 'n_paso']

	def __str__(self):
		return '%s %s'% (self.n_paso, self.nombre)


class TipoFuente(models.Model):
	tipo = models.CharField(max_length = 30, verbose_name="tipo de fuente")
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta():
		verbose_name_plural = "Tipos de fuentes"
		ordering = ['tipo']

	def __str__(self):
		return '%s'% (self.tipo)


class RequisitoPaso(models.Model):
	id_paso = models.ForeignKey(Paso, on_delete = models.CASCADE)
	tipo_fuente = models.ForeignKey(TipoFuente, on_delete = models.PROTECT)
	nombre_fuente = models.CharField(max_length = 50, verbose_name = "nombre tabla fuente")
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta():
		verbose_name_plural = "Requisitos de paso"
		ordering = ['id', 'id_paso']

	def __str__(self):
		return '%s %s'% (self.tipo_fuente, self.nombre_fuente)

AdminLTE3/views.py
from django.shortcuts import render

# Create your views here.

docs/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Reporte


class IndexView(generic.ListView):
	template_name = 'docs/index.html'
	context_object_name = 'reporte_list'

	def get_queryset(self):
		return Reporte.objects.order_by('id')



class ReporteView(generic.DetailView):
	model = Reporte
	template_name = 'docs/reporte.html'



def pasos_reporte(request, id_reporte):
  detalle = "Estas buscando los pasos del reporte %s."
  return HttpResponse(detalle % id_reporte)

AdminLTE3/templates/AdminLTE3/_dataTables_css.html
{% load static %}

<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'a_dist/css/adminlte.min.css' %}">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

AdminLTE3/templates/AdminLTE3/_dataTables_js.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'a_dist/js/adminlte.min.js' %}"></script>

AdminLTE3/templates/AdminLTE3/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    
    {% block title_outer %}
    <title> {% block title %} {{ site.name }} {% endblock title %} </title>
    {% endblock title_outer %}

    {% block css %}
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'a_dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    {% block extra_css %}  {% endblock extra_css %}
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    {% endblock css %}

  </head>
  <body 
    {% block body_class %} class="hold-transition layout-top-nav" {% endblock body_class %} 
    {% block body_style %} style="height: auto;" {% endblock body_style %}>
    <div class="wrapper">

      <!-- Navbar -->
      <nav {% block navbar_class %} class="main-header navbar navbar-expand-md navbar-dark" {% endblock navbar_class %} >
      {% block navbar %}
        <div class="container">

          {% block navbar_brad %}
          <span class="navbar-brand">
            <img src="{% static 'img/Tottus.png' %}" alt="AdminLTE Logo" class="brand-image" style="opacity: .8">
          </span>
          {% endblock navbar_brad %}

          <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
            {% block navbar_left_links %}
              <li class="nav-item">
                <a href=" {% url 'docs:index' %} " class="nav-link">Home</a>
              </li>
            {% endblock navbar_left_links %}
            </ul>
          </div>

          <!-- Right navbar links -->
          <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
          {% block navbar_rigth_links %}
          {% endblock navbar_rigth_links %}
          </ul>

        </div>
      {% endblock navbar %}
      </nav>
      <!-- /.navbar -->

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0 text-dark">{% block content_title %}Titulo de contenido{% endblock content_title %}<small>{% block content_title_small %}{% endblock content_title_small %}</small>
                </h1>
              </div><!-- /.col -->
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  {% block breadcrumb %}
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">Starter Page</li>
                  {% endblock breadcrumb %}
                </ol>
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
          <div class="container-fluid">
          {% block content %}
          {% endblock content %}
          </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the right -->
        {% block footer %}
        <div class="float-right d-none d-sm-inline">
          {% block footer_right %}
          Gerencia Desarrollo Logistico - Gestion de Informacion
          {% endblock footer_right %}
        </div>
        <!-- Default to the left -->
        {% block footer_left %}
        <strong>Correo de soporte: <a href="mailto:desarrollo.logistico.tottus@falabella.cl"> desarrollo.logistico.tottus@falabella.cl </a> </strong>
        {% endblock footer_left %}
        {% endblock footer %}
      </footer>
    </div>
    <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->

  {% block js %}
  <!-- jQuery -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap 4 -->
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'js/adminlte.min.js' %}"></script>
  {% block extra_js %}{% endblock extra_js %}
  {% endblock js %}
  </body>
</html>

docs/templates/docs/index.html
{% extends 'AdminLTE3/base.html' %}
{% load i18n static %}

{% block css %}
	{% include 'AdminLTE3/_dataTables_css.html' %}
{% endblock css %}

{% block content_title %} Reportes {% endblock content_title %}
{% block content_title_small %}(Lista){% endblock content_title_small %}

{% block breadcrumb %} 
{% endblock breadcrumb %}

{% block content %}

<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-header">
			<h3 class="card-title">Lista de Reportes</h3>
			</div>
			<div class="card-body">
			{% if reporte_list %}
			<table id="datatable" class="table table-bordered table-striped table-sm">
				<thead>
					<tr>
						<th>id</th>
						<th>Reporte</th>
						<th>Solicitante</th>
						<th>Responsable</th>
						<th>Prioridad</th>
						<th>Servidor</th>
						<th>Dias</th>
						<th>Hora</th>
						<th>Status</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
				{% for reporte in reporte_list %}
					<tr>
						<td> {{ reporte.id }} </td>
						<td> <a href=" {% url 'docs:reporte' reporte.id %} "> {{ reporte.nombre }} </a> </td>
						<td> {{ reporte.solicitante }} </td>
						<td> {{ reporte.responsable.first_name }} {{ reporte.responsable.last_name }} </td>
						<td> {{ reporte.get_prioridad_display }} </td>
						<td> {{ reporte.servidor }} </td>
						<td> {% for dia in reporte.dias.all %} {{ dia.id }} {% endfor %} </td>
						<td> {{ reporte.hora_actualizacion}} </td>
						<td><span class="badge badge-success">success</span></td>
						<td> 
							<a class="btn btn-outline-info btn-xs" href=" {% url 'docs:reporte' reporte.id %} "> <i class="fas fa-info-circle"></i> info </a>
							<a class="btn btn-outline-warning btn-xs" href="#"> <i class="far fa-edit"></i></i> edit </a>
						</td>
					</tr>
					{% comment %} <li><a href="{% url 'docs:reporte' reporte.id %}">{{ reporte.nombre }}</a></li> {% endcomment %}
				{% endfor %}
				</tbody>
				<tfoot>
					<tr>
						<th>id</th>
						<th>Reporte</th>
						<th>Solicitante</th>
						<th>Responsable</th>
						<th>Prioridad</th>
						<th>Servidor</th>
						<th>Dias</th>
						<th>Hora</th>
						<th>Status</th>
						<th>Acciones</th>
					</tr>
				</tfoot>
			</table>
			{% else %}
				<p>No hay reportes registrados</p>
			{% endif %}

			</div>
		</div>
	</div>
</div>

{% endblock content %}

{% block js %}
	{% include 'AdminLTE3/_dataTables_js.html' %}
	<script>
  $(document).ready(function () {
    $('#datatable').DataTable();
  });
</script>
{% endblock js %}

docs/templates/docs/reporte.html
{% extends 'AdminLTE3/base.html' %}

{% block content_title %}{{ reporte.nombre }}{% endblock content_title %}
{% block content_title_small %} ({{reporte.solicitante}}) {% endblock content_title_small %}

{% if error_message %}<p><strong> {{ error_message }} </strong></p>{% endif %}

{% block content %}
<ul><strong>Pasos</strong>
	{% for paso in reporte.paso_set.all %}
	<li>{{ paso }}
		<ul> <strong> Requisitos de paso </strong>
			{% for requisito in paso.requisitopaso_set.all %}
				<li> {{ requisito }} </li>
			{% endfor %}
		</ul>
	</li>
	{% endfor %}
</ul>
<a href="{% url 'docs:index' %}">Atrás</a>
{% endblock content %}